.\" ident "@(#)dapro/syn03/lexcond.5 1.1 01/23/98"
.TH LEXCOND 5 "01/23/98" "Werkgroep Informatica" "BIBLICAL LANGUAGES"
.SH NAME
lexcond \- lexemes for the lexical conditions
.SH DESCRIPTION
The file
.B lexcond
contains the list of lexemes that correspond with the lexical
conditions used in
.BR phrset (5).
The lexemes are listed one to a line. Each line consists of
nothing but the lexeme.
Lexical conditions are referenced through positive integers
that correspond with the line number in this file.
A condition is met when the word in question has a lexeme that is
identical to the one stated on the indicated line.
.PP
In
.BR phrset (5)
lexical conditions are listed with an offset of 100 in order to
discriminate them from morphological conditions. E.g. condition
105 in
.BR phrset (5)
stands for lexical condition number 5.
.SH SEE ALSO
.BR syn03 (1),
.BR morfcond (5),
.BR phrset (5).
