h45884
s 00024/00000/00000
d D 1.1 98/01/23 16:19:03 const 1 0
c date and time created 98/01/23 16:19:03 by const
e
u
U
f e 0
f m dapro/syn03/ps2phd.1
t
T
I 1
.\" ident "%Z%%M% %I% %G%"
.TH PS2PHD 1 "%G%" "Werkgroep Informatica" "BIBLICAL LANGUAGES"
.SH NAME
ps2phd \- derive PHD file from PS file
.SH SYNOPSIS
.BR ps2phd " [ \fIfile\fR ]"
.SH DESCRIPTION
.B ps2phd
recreates a
.BR phd (5)
file from the phrase divisions found in a
.BR ps3 (5)
file.
It takes one argument, the
.SM PS
file, and writes its output to
.IR stdout .
If no arguments are specified,
.I stdin
is read.
.SH "SEE ALSO"
.BR phd (5),
.BR ps3 (5),
.BR syn03 (1).
E 1
