MESA 01,01 [>NK <Su>] [MC< / BN KMCJT MLK M>B H-DJBNJ <ap><PC>]
MESA 01,02 [>B-J <Su>] [MLK <Pr>] [<L M>B <Aj>] [CLCN CT <Aj>]
MESA 01,02 [W-<Cj>] [>NK <Su>] [MLKTJ <Pr>] [>XR >B-J <Aj>]
MESA 01,03 [W-<Cj>] [><F <Pr>] [H-BMT Z>T <Ob>] [L-KMC <Aj>] [B-QRXH <Lo>]
MESA 01,04 [BMT JC< <Ob>]
MESA 01,04 [KJ <Cj>] [HC<-<Pr>] [NJ <Ob>] [M-KL H-MLKN <Co>]
MESA 01,04 [W-<Cj>] [KJ <Cj>] [HR>-<Pr>] [NJ <Ob>] [B-KL FN>-J <Co>]
MESA 01,05 [<MRJ <Su>] [MLK JFR>L <PC>]
MESA 01,05 [W-<Cj>] [J<NW <Pr>] [>T M>B <Ob>] [JMN RBN <Aj>]
MESA 01,05 [KJ <Cj>] [J>NP <Pr>] [KMC <Su>] [B->RY-H <Co>]
MESA 01,06 [W-<Cj>] [JXLP-<Pr>] [H <Ob>] [BN-H <Ob>]
MESA 01,06 [W-<Cj>] [J>MR <Pr>] [GM H> <Su>]
MESA 01,06 [><NW <Pr>] [>T M>B <Ob>]
MESA 01,07 [B-JMJ- <Ti>] [>MR <Pr>] [KN <Mo>]
MESA 01,07 [W-<Cj>] [>R> <Pr>] [B-H W-B-BT-H <Co>]
MESA 01,08 [W-<Cj>] [JFR>L <Su>] [>BD <Mo>] [>BD <Pr>] [<LM <Ti>]
MESA 01,08 [W-<Cj>] [JRC <Pr>] [<MRJ <Su>] [>T KL >RY MHDBH <Ob>]
MESA 01,09 [W-<Cj>] [JCB <Pr>] [B-H <Co>] [JM-H / W-/ XYJ JMJ BN-H / >RB<N CT <sp><pa><cj><Ti>]
MESA 01,09 [W-<Cj>] [JCB-<Pr>] [H <Ob>] [KMC <Su>] [B-JMJ- <Ti>]
MESA 01,10 [W-<Cj>] [>BN <Pr>] [>T B<LM<N <Ob>]
MESA 01,10 [W-<Cj>] [><F <Pr>] [B-H <Aj>] [H->CWX <Ob>]
MESA 01,10 [W-<Cj>] [>BN <Pr>] [>T QRJTN <Ob>]
MESA 01,11 [W-<Cj>] [>C GD <Su>] [JCB <Pr>] [B->RY <VRT <Co>] [M-<LM <Ti>]
MESA 01,11 [W-<Cj>] [JBN <Pr>] [L-H <Aj>] [MLK JFR>L <Su>] [>T <VRT <Ob>]
MESA 01,12 [W-<Cj>] [>LTXM <Pr>] [B--QR <Co>]
MESA 01,12 [W-<Cj>] [>XZ-<Pr>] [H <Ob>]
MESA 01,13 [W-<Cj>] [>HRG <Pr>] [>T KL H-<M M-H-QR <Ob>]
MESA 01,13 [HJT <Pr>] [L-KMC W-L-M>B <PC>]
MESA 01,14 [W-<Cj>] [>CB <Pr>] [M-CM <Co>] [>T >R>L DWDH <Ob>]
MESA 01,14 [W-<Cj>] [>SXB-<Pr>] [H <Ob>] [L-PNJ KMC <Co>] [B-QRJT <Lo>]
MESA 01,15 [W-<Cj>] [>CB <Pr>] [B-H <Co>] [>T >C CRN W->T >C MXRT <Ob>]
MESA 01,16 [W-<Cj>] [J>MR <Pr>] [L-J <Co>] [KMC <Su>]
MESA 01,16 [LK <Pr>]
MESA 01,16 [>XZ <Pr>] [>T NBH <Ob>] [<L JFR>L <Aj>]
MESA 01,17 [W-<Cj>] [>HLK <Pr>] [B--LLH <Ti>]
MESA 01,17 [W-<Cj>] [>LTXM <Pr>] [B-H <Co>]
MESA 01,17 [M-BQ< <Pr>] [H-CXRT <Su>]
MESA 01,17 [<D H-YHRM <Ti>]
MESA 01,18 [W-<Cj>] [>XZ-<Pr>] [H <Ob>]
MESA 01,18 [W-<Cj>] [>HRG <Pr>] [KL-H / CB<T >LPN GBRN W-GRN <sp><Ob>]
MESA 01,19 [W-<Cj>] [GBRT W-GRT W-RXMT <Ob>]
MESA 01,20 [KJ <Cj>] [L-<CTR KMC <Co>] [HXRMT-<Pr>] [H <Ob>]
MESA 01,21 [W-<Cj>] [>QX <Pr>] [M-CM <Co>] [>T KLJ JHWH <Ob>]
MESA 01,21 [W-<Cj>] [>SXB <Pr>] [HM <Ob>] [L-PNJ KMC <Co>]
MESA 01,22 [W-<Cj>] [MLK JFR>L <Su>] [BNH <Pr>] [>T JHY <Ob>]
MESA 01,22 [W-<Cj>] [JCB <Pr>] [B-H <Co>]
MESA 01,22 [B-HLTXM-<Pr>] [H <Su>] [B-J <Co>]
MESA 01,23 [W-<Cj>] [JGRC-<Pr>] [H <Ob>] [KMC <Su>] [M-PNJ- <Co>]
MESA 01,24 [W-<Cj>] [>QX <Pr>] [M-M>B <Co>] [M>TN >C / KL RC-H <sp><Ob>]
MESA 01,25 [W-<Cj>] [>F>-<Pr>] [H <Ob>] [B-JHY <Co>]
MESA 01,25 [W-<Cj>] [>XZ-<Pr>] [H <Ob>]
MESA 01,25 [L-SPT <Pr>] [<L DJBN <Co>]
MESA 01,26 [>NK <Su>] [BNTJ <Pr>] [QRXH / XMT H-J<RN W-XMT H-<PL <sp><Ob>]
MESA 01,27 [W-<Cj>] [>NK <Su>] [BNTJ <Pr>] [C<RJ-H <Ob>]
MESA 01,27 [W-<Cj>] [>NK <Su>] [BNTJ <Pr>] [MGDLT-H <Ob>]
MESA 01,28 [W-<Cj>] [>NK <Su>] [BNTJ <Pr>] [BT MLK <Ob>]
MESA 01,28 [W-<Cj>] [>NK <Su>] [<FTJ <Pr>] [KL>J H->CWX <Ob>] [B-M<JN / B-QRB H-QR <sp><Lo>]
MESA 01,29 [W-<Cj>] [BR <Su>] [>N <eX>] [B-QRB H-QR / B--QRXH <sp><PC>]
MESA 01,29 [W-<Cj>] [>MR <Pr>] [L-KL H-<M <Co>]
MESA 01,29 [<FW <Pr>] [L-KM <Aj>]
MESA 01,29 [>C <Su>] [BR <Ob>] [B-BJT-H <Lo>]
MESA 01,30 [W-<Cj>] [>NK <Su>] [KRTJ <Pr>] [H-MKRTT <Ob>] [L--QRXH <Co>] [B->SRJ JFR>L <Aj>]
MESA 01,31 [>NK <Su>] [BNTJ <Pr>] [<R<R <Ob>]
MESA 01,31 [W-<Cj>] [>NK <Su>] [<FTJ <Pr>] [H-MSLT <Ob>] [B->RNN <Lo>]
MESA 01,32 [W-<Cj>] [>NK <Su>] [BNTJ <Pr>] [BT BMT <Ob>]
MESA 01,32 [KJ <Cj>] [HRS <PC>] [H> <Su>]
MESA 01,33 [>NK <Su>] [BNTJ <Pr>] [BYR <Ob>]
MESA 01,33 [KJ <Cj>] [<JN <PC>] [H> <Su>]
MESA 01,33 [B->C DJBN XMCN <Aj>]
MESA 01,33 [KJ <Cj>] [KL DJBN <Su>] [MCM<T <PC>]
MESA 01,34 [W-<Cj>] [>NK <Su>] [MLKTJ <Pr>] [<L H-M>T <Co>] [B--QRN <Lo>]
MESA 01,34 [>CR <Re>] [JSPTJ <Pr>] [<L H->RY <Co>]
MESA 01,35 [W-<Cj>] [>NK <Su>] [BNTJ <Pr>] [GM MHDB> W-BT DBLTN <Ob>]
MESA 01,36 [W-<Cj>] [BT B<LM<N <Ob>]
MESA 01,36 [W-<Cj>] [>F> <Pr>] [CM <Lo>] [>T NQ DJ <Ob>]
MESA 01,36 [L-R<T <Pr>] [>T Y>N H->RY <Ob>]
MESA 01,37 [W-<Cj>] [XWRNN <Fr>]
MESA 01,37 [JCB <Pr>] [BT DWD <Su>] [B <..>] [WQ <..>] [>C <..>]
MESA 01,37 [W-<Cj>] [J>MR <Pr>] [L-J <Co>] [KMC <Su>]
MESA 01,37 [RD <Pr>]
MESA 01,37 [HLTXM <Pr>] [B-XWRNN <Co>]
MESA 01,38 [W-<Cj>] [>RD <Pr>] [W>L <..>] [TXM <..>] [B--QR <Co>]
MESA 01,38 [W-<Cj>] [>XZ-<Pr>] [H <Ob>]
MESA 01,38 [W-<Cj>] [JCB <Pr>] [B-H <Co>] [KMC <Su>] [B-JMJ- <Ti>]
MESA 01,38 [W-<Cj>] [<L <PC>] [DH <..>] [M-CM <Lo>] [<C <..>] [CT <..>] [CDQ <..>]
MESA 01,39 [W-<Cj>] [>NK <Su>]
